version: "3.9"  # optional since v1.27.0
services:
  coturn:
    image: instrumentisto/coturn
    container_name: web
    ports:
      - 3478:3478
      - 49152-49500:49152-49500
    command: docker-entrypoint.sh --min-port 49160 --max-port 49500 
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
# docker run -d -p 3478:3478 -p 49152-49500:49152-49500/udp instrumentisto/coturn --min-port 49160 --max-port 49500 -v C:/users/c1419/Documents/Github/portofolio/turnserver.conf:/etc/coturn/turnserver.conf;