version: '3'
services:
  socketio:
    build: .
    ports:
      - "2000:2000"
    command: sh /usr/src/app/dev.sh
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - "./ws-server:/usr/src/app"
      - "./ssl/main:/etc/letsencrypt"
      - "../visitors/:/usr/src/app/visitors/"
      - "./ssl/lib:/var/lib/letsencrypt"
