version: '3'
services:
  socketio:
    build: .
    # build: 
    #   context: ./dockerfiles
    #   dockerfile: Dockerfile
    tty: true
    ports:
      - "2000:2000"
    command: sh /usr/src/app/prod.sh
    volumes:
      - "./ws-server:/usr/src/app"
      - "./ssl/main:/etc/letsencrypt"
      - "./ssl/lib:/var/lib/letsencrypt"
