name: Pulling new Source Code to deploy-server

on:
  push:
    branches: [master]
  

jobs:
  build_deploy: 
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # - uses: actions/checkout@v2
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Files
        run: bash ./build.sh -m PROD --use-docker
        continue-on-error: true
      - name: Go to outside dir
        run: cd ../
      - name: Clone JohansenJunias20 Repository (deploy directory)
        run: git clone https://JohansenJunias20:${{ secrets.PASSWORD }}@github.com/JohansenJunias20/JohansenJunias20.github.io.git
      - name: Copy build files to deploy directory
        run: ls; cp -r portofolio/public/* ./JohansenJunias20.github.io/
      - name: Change Directory to deploy directory
        run: cd ./JohansenJunias20.github.io
      - name: Push to Deploy Repository
        run: git add .; git commit -m "new changes";git push https://JohansenJunias20:${{ secrets.PASSWORD }}@github.com/JohansenJunias20/JohansenJunias20.github.io.git;